name = "Newb X Calm Vibes"
version = [5, 0, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- Shader specialized to bring an immersive experience and relaxing vibes to your survival.
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["devendrn", "SkibidiBoiler"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "fe5c235b-c2a2-45d2-87d6-91bad2166338" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2024 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
SkibidiBoiler
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Box Clouds
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk loading animation
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
