name: build

on:
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: 'platform'
        required: true
        default: 'All'
        type: choice
        options:
        - Android
        - Windows
        - IOS
        - Merged
        - All

jobs:
  windows:
    runs-on: windows-2022
    if:  ${{ (github.event.inputs.platform == 'Windows') || (github.event.inputs.platform == 'All') }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-win-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        .\build.bat setup
        .\build.bat pack -p windows -v ${{ inputs.subversion }}
        Get-ChildItem -Path ./build
        $mcpack = Get-ChildItem -Path ./build -Filter "*.mcpack" | Select-Object -First 1
        if ($mcpack) {
        Rename-Item -Path $mcpack.FullName -NewName "newb-x-windows.mcpack"
        } else {
        Write-Error "No .mcpack file found. Check build.bat or shader compilation."
        exit 1
        }
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-windows.mcpack
        path: ./build/newb-x-windows.mcpack
  android:
    runs-on: ubuntu-latest
    if:  ${{ (github.event.inputs.platform == 'Android') || (github.event.inputs.platform == 'All') }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-linux-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        ./build.sh setup
        ./build.sh pack -p android -v ${{ github.event.inputs.subversion }}
        echo "Checking build directory..."
        ls -R ./build
        if [ -f ./build/pack-android.zip ]; then
        mv ./build/pack-android.zip newb-x-android.mcpack
        elif ls ./build/*.mcpack 1> /dev/null 2>&1; then
        mcpack_file=$(ls ./build/*.mcpack | head -n 1)
        mv "$mcpack_file" newb-x-android.mcpack
        else
        echo "Error: Expected file not found in ./build"
        exit 1
        fi
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-android
        path: ./newb-x-android.mcpack
  ios:
    runs-on: ubuntu-latest
    if:  ${{ (github.event.inputs.platform == 'IOS') || (github.event.inputs.platform == 'All') }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-linux-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        ./build.sh setup
        ./build.sh pack -p ios -v ${{ inputs.subversion }}
        mv ./build/pack-ios.zip newb-x-ios.mcpack
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-ios.mcpack
        path: ./newb-x-ios.mcpack
  merged:
    runs-on: windows-2022
    if:  ${{ (github.event.inputs.platform == 'Merged') || (github.event.inputs.platform == 'All')}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-win-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        .\build.bat setup
        .\build.bat pack -p merged -v ${{ inputs.subversion }}
        echo "Debug: Checking for pack-merged.zip"
        if (Test-Path -Path ./build/pack-merged.zip) {
        Rename-Item -Path ./build/pack-merged.zip -NewName newb-x-merged.mcpack
        } else {
        Write-Error "Error: pack-merged.zip not found in ./build"
        exit 1
        }
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-merged.mcpack
        path: ./build/newb-x-merged.mcpack
